### ISSUE TITLE
long-format for phyloprofile input

### ISSUE THREAD

**Issue by trvinh** [BIONF/HaMStR#2]
Since the [matrix file](https://github.com/BIONF/PhyloProfile/wiki/Input-Data#wide-matrix-format) does not support co-orthologs, we need to use the [long format](https://github.com/BIONF/PhyloProfile/wiki/Input-Data#long-format).

@holgerbgm you can use my script here to replace the current `parseOneSeq.pl`
[parseOneSeq_mod.pl.txt](https://github.com/BIONF/HaMStR/files/1841839/parseOneSeq_mod.pl.txt)
*(remove the `.txt` extension after copying)*

**Usage:**
`perl parseOneSeq_mod.pl -i <path_to_hamstr_output> -o <job_name.profile>`

where `path_to_hamstr_output` is the folder that contains `*.extended.profile` files.

**Comment by ebersber** [comment]
I thought this issue is fixed? Can we close it?

**Comment by trvinh** [comment]
Yes of course!
