### ISSUE TITLE
CAST not working

### ISSUE THREAD

**Issue by cagescudero** [BIONF/HaMStR#25]
Hello

I am manually creating a new data set. In the step 6 (Create the annotation files for your taxon with the provided perl script) I get the following error:

```
Can't exec "/home/ubuntu/annotation_fas/CAST/cast": No such file or directory at /home/ubuntu/anaconda3/envs/hamstr/lib/python3.8/site-packages/greedyFAS/annoFAS.pl line 909.
Use of uninitialized value $castOut in scalar chomp at /home/ubuntu/anaconda3/envs/hamstr/lib/python3.8/site-packages/greedyFAS/annoFAS.pl line 910.
Use of uninitialized value $castOut in concatenation (.) or string at /home/ubuntu/anaconda3/envs/hamstr/lib/python3.8/site-packages/greedyFAS/annoFAS.pl line 911.
```

I used the following command:
```
annoFAS --fasta=/home/ubuntu/tools/HaMStR/genome_dir/TEST@00001@1/TEST@00001@1.fa --path=/home/ubuntu/tools/HaMStR/weight_dir --name=TEST@00001@1
```

It seems that CAST is not compiled to work with our system. I couldn't find the CAST v1.0 on their webpage.

Best,
Cata

**Comment by trvinh** [comment]
Hi Cata,
can you check if you have the folder **cast** at `/home/ubuntu/annotation_fas/` and if that folder contains any things or just empty? If it is not empty, please try to run **cast** directly from there to see if it works. 
Let me know more after you checked those points. Many thanks 😊

**Comment by cagescudero** [comment]
Hello,

The folder is there and the executable of cast too. However, when I try to tun the code alone is not working.

```
~/annotation_fas/CAST/$ ./cast 
-bash: ./cast: No such file or directory
```

Also, I tried to use the `cast.zip` (after unzipping) that is located in the same directory but I get the same error.

```
~/annotation_fas/CAST/cast-linux$ ./cast 
-bash: ./cast: No such file or directory
```

Best,
Cata

**Comment by trvinh** [comment]
@Cataescuderoo 
could you please go to the CAST folder and do
```
ls -la
```
then send me the screen shot?

**Comment by cagescudero** [comment]
@trvinh 
Here it is.

```
~/annotation_fas/CAST$ ls -la
total 428
drwxr-xr-x 4 ubuntu ubuntu   4096 Feb  7 13:48 .
drwxrwxr-x 9 ubuntu ubuntu   4096 Jan 21 16:41 ..
-rwxr-xr-x 1 ubuntu ubuntu  18009 May  3  2017 LICENSE
-rwxr-xr-x 1 ubuntu ubuntu   1405 May  3  2017 README
-rwxr-xr-x 1 ubuntu ubuntu  22892 May  3  2017 cast
drwxr-x--- 2 ubuntu ubuntu   4096 Feb  7 13:38 cast-linux
-rw-r--r-- 1 ubuntu ubuntu 370555 May  3  2017 cast.zip
drwxr-xr-x 2 ubuntu ubuntu   4096 Feb  7 17:01 tmp
```

**Comment by trvinh** [comment]
can you also do
```
file cast
```
to see if it is executable?

**Comment by cagescudero** [comment]
```
~/annotation_fas/CAST$ file cast
cast: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, for GNU/Linux 2.0.0, not stripped
```

**Comment by trvinh** [comment]
Probably your computer system (is it a ubuntu 64 bit?) doesn't have the libraries for running 32-bit tools. Please check this link https://askubuntu.com/questions/454253/how-to-run-32-bit-app-in-ubuntu-64-bit to see if it can solve this problem.

**Comment by cagescudero** [comment]
CAST is working now after installing the 32 bit libraries. Thanks!
