### ISSUE TITLE
For loop not working

### ISSUE THREAD

**Issue by cagescudero** [BIONF/HaMStR#28]
Hello

I tried running a loop for different proteins using the following command:

`for PROTEIN in *fa; do oneSeq -seqFile=$PROTEIN -seqname=$PROTEIN -refspec=HUMAN@9606@1 -minDist=genus -maxDist=phylum -coreOrth=5 -cleanup -global -cpu=20 -countercheck; done`

It runs with the first protein until it creates the *.extended.fa file and then it starts doing the second protein without any other output for the first protein. If I run the proteins one by one it works fine. 

Best,
Cata

**Comment by ebersber** [comment]
Hi Cata,
I quickly checked it, and the option 'seqname=$PROTEIN' in your loop causes the trouble. In your loop, $PROTEIN will be interpolated as YOURFILENAME.fa (please note the 'dot' in the file name). In the course of the FAS annotation, oneSeq will attempt to generate a directory that is called like what you specified via the option -seqname. In your case, it will try to generate a sub-directory called YOURFILENAME.fa in a directory that already contains the FILE YOURFILENAME.fa. As a consequence, it throws the following error: 
mkdir /home/ingo/HaMStR/data/infile.fa: **File exists at ../bin/oneSeq line 558** 
and it will then die. 

**Solution:** 
Modifie your loop in the following way:
for PROTEIN in *fa; do NAME=`echo $PROTEIN | sed -e 's/\.fa//'`; oneSeq -seqFile=$PROTEIN -seqname=$NAME -refspec=HUMAN@9606@1 -minDist=genus -maxDist=phylum -coreOrth=5 -cleanup -global -cpu=20 -countercheck; done

Let me know if this solves the problem.

Best,

Ingo
